### ISSUE TITLE
App crash on old Tablet when trying XLXS export

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1315]
Description:

For some reason my old Galaxy Tab OS12 crashes when trying to choose XLXS export.
This works on S10+ with OS12 and no issues on my test phones.

This is a low priority bug.

https://github.com/user-attachments/assets/a45c1d7d-2a60-4b8f-bf2e-74b350ac460c

**Comment by andreevdenis** [comment]
Tested with Galaxy Tab S7 with Android 12. Works ok, no crashes.Maybe some specific settings on this device? Regional settings? Do you export same sensor with phone and tablet?

**Comment by andreevdenis** [comment]
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDate;
       at retrofit2.Platform$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass)
       at uk.co.spudsoft.xlsx.XlsxWriter.<clinit>(XlsxWriter.java:58)
       at com.ruuvi.station.tagsettings.domain.XlsxExporter.exportToXlsx(XlsxExporter.kt:77)
       at com.ruuvi.station.tagdetails.ui.SensorCardViewModel.exportToXlsx(SensorCardViewModel.kt:199)
       at com.ruuvi.station.tagdetails.ui.SensorCardActivity$onCreate$1$1$11.invoke(SensorCardActivity.kt:134)
       at com.ruuvi.station.tagdetails.ui.SensorCardActivity$onCreate$1$1$11.invoke(SensorCardActivity.kt:134)
       at com.ruuvi.station.graph.ChartControlElementKt$ChartControlElement2$2$3$2$1.invoke(ChartControlElement.kt:146)
       at com.ruuvi.station.graph.ChartControlElementKt$ChartControlElement2$2$3$2$1.invoke(ChartControlElement.kt:146)
       at com.ruuvi.station.graph.ChartControlElementKt$ThreeDotsMenu$1$3$2.invoke(ChartControlElement.kt:343)
       at com.ruuvi.station.graph.ChartControlElementKt$ThreeDotsMenu$1$3$2.invoke(ChartControlElement.kt:342)
       at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke-k-4lQ0M(Clickable.kt:639)
       at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:633)
       at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:719)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:598)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:620)
       at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:1044)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:387)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373)
       at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:229)
       at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:144)
       at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:120)
       at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1993)
       at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1944)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1828)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.View.dispatchPointerEvent(View.java:10344)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by andreevdenis** [comment]
Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDate" on path: DexPathList[[zip file "/data/app/com.ruuvi.station-1/base.apk", zip file "/data/app/com.ruuvi.station-1/split_config.armeabi_v7a.apk", zip file "/data/app/com.ruuvi.station-1/split_config.tvdpi.apk"],nativeLibraryDirectories=[/data/app/com.ruuvi.station-1/lib/arm, /data/app/com.ruuvi.station-1/base.apk!/lib/armeabi-v7a, /data/app/com.ruuvi.station-1/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.ruuvi.station-1/split_config.tvdpi.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at retrofit2.Platform$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass)
       at uk.co.spudsoft.xlsx.XlsxWriter.<clinit>(XlsxWriter.java:58)
       at com.ruuvi.station.tagsettings.domain.XlsxExporter.exportToXlsx(XlsxExporter.kt:77)
       at com.ruuvi.station.tagdetails.ui.SensorCardViewModel.exportToXlsx(SensorCardViewModel.kt:199)
       at com.ruuvi.station.tagdetails.ui.SensorCardActivity$onCreate$1$1$11.invoke(SensorCardActivity.kt:134)
       at com.ruuvi.station.tagdetails.ui.SensorCardActivity$onCreate$1$1$11.invoke(SensorCardActivity.kt:134)
       at com.ruuvi.station.graph.ChartControlElementKt$ChartControlElement2$2$3$2$1.invoke(ChartControlElement.kt:146)
       at com.ruuvi.station.graph.ChartControlElementKt$ChartControlElement2$2$3$2$1.invoke(ChartControlElement.kt:146)
       at com.ruuvi.station.graph.ChartControlElementKt$ThreeDotsMenu$1$3$2.invoke(ChartControlElement.kt:343)
       at com.ruuvi.station.graph.ChartControlElementKt$ThreeDotsMenu$1$3$2.invoke(ChartControlElement.kt:342)
       at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke-k-4lQ0M(Clickable.kt:639)
       at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:633)
       at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:719)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:598)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:620)
       at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:1044)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:387)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373)
       at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:229)
       at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:144)
       at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:120)
       at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1993)
       at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1944)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1828)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.View.dispatchPointerEvent(View.java:10344)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by markoaamunkajo** [comment]
QA passed
Language strings will come in next build
